In [16]:
import pandas as pd

print(pd.__version__)
import tensorflow as tf
print(tf.__version__)

from tensorflow.keras.models import Sequential # type: ignore
from tensorflow.keras.layers import Dense, Dropout # type: ignore

# sklearn
from sklearn.model_selection import train_test_split # type: ignore
from sklearn.preprocessing import MinMaxScaler,LabelEncoder # type: ignore


2.2.3
2.19.0


In [17]:
df = pd.read_csv("metadata.csv")
df

type                                         start_time  \
0     discharge  [2010.       7.      21.      15.       0.    ...   
1     impedance  [2010.       7.      21.      16.      53.    ...   
2        charge  [2010.       7.      21.      17.      25.    ...   
3     impedance                    [2010    7   21   20   31    5]   
4     discharge  [2.0100e+03 7.0000e+00 2.1000e+01 2.1000e+01 2...   
...         ...                                                ...   
7560  impedance  [2010.       9.      30.       7.      36.    ...   
7561  discharge  [2010.       9.      30.       8.       8.    ...   
7562     charge  [2010.      9.     30.      8.     48.     54.25]   
7563  discharge  [2010.       9.      30.      11.      50.    ...   
7564     charge  [2010.       9.      30.      12.      31.    ...   

      ambient_temperature battery_id  test_id   uid   filename  \
0                       4      B0047        0     1  00001.csv   
1                      24      B0047        1     2  00002.csv   
2                       4      B0047        2     3  00003.csv   
3                      24      B0047        3     4  00004.csv   
4                       4      B0047        4     5  00005.csv   
...                   ...        ...      ...   ...        ...   
7560                   24      B0055      247  7561  07561.csv   
7561                    4      B0055      248  7562  07562.csv   
7562                    4      B0055      249  7563  07563.csv   
7563                    4      B0055      250  7564  07564.csv   
7564                    4      B0055      251  7565  07565.csv   

                Capacity                   Re                  Rct  
0     1.6743047446975208                  NaN                  NaN  
1                    NaN  0.05605783343888099  0.20097016584458333  
2                    NaN                  NaN                  NaN  
3                    NaN  0.05319185850921101  0.16473399914864734  
4     1.5243662105099023                  NaN                  NaN  
...                  ...                  ...                  ...  
7560                 NaN   0.0968087979207628  0.15489738203707232  
7561  1.0201379996149256                  NaN                  NaN  
7562                 NaN                  NaN                  NaN  
7563  0.9907591663373165                  NaN                  NaN  
7564                 NaN                  NaN                  NaN  

[7565 rows x 10 columns]

In [18]:
df = df.drop(columns=['start_time','battery_id','test_id','uid','filename'])
df

type  ambient_temperature            Capacity                   Re  \
0     discharge                    4  1.6743047446975208                  NaN   
1     impedance                   24                 NaN  0.05605783343888099   
2        charge                    4                 NaN                  NaN   
3     impedance                   24                 NaN  0.05319185850921101   
4     discharge                    4  1.5243662105099023                  NaN   
...         ...                  ...                 ...                  ...   
7560  impedance                   24                 NaN   0.0968087979207628   
7561  discharge                    4  1.0201379996149256                  NaN   
7562     charge                    4                 NaN                  NaN   
7563  discharge                    4  0.9907591663373165                  NaN   
7564     charge                    4                 NaN                  NaN   

                      Rct  
0                     NaN  
1     0.20097016584458333  
2                     NaN  
3     0.16473399914864734  
4                     NaN  
...                   ...  
7560  0.15489738203707232  
7561                  NaN  
7562                  NaN  
7563                  NaN  
7564                  NaN  

[7565 rows x 5 columns]

In [19]:
df['Re'] = pd.to_numeric(df['Re'], errors='coerce')
df['Rct'] = pd.to_numeric(df['Rct'], errors='coerce')
df['Capacity'] = pd.to_numeric(df['Capacity'], errors='coerce')

In [20]:
df['Re'].fillna(df['Re'].mean(), inplace=True)
df['Rct'].fillna(df['Rct'].mean(), inplace=True)
df['Capacity'].fillna(df['Capacity'].mean(), inplace=True)

df

/var/folders/2f/qb3_fbjx1s994zz02ncpnfth0000gn/T/ipykernel_2441/1658380151.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Re'].fillna(df['Re'].mean(), inplace=True)
/var/folders/2f/qb3_fbjx1s994zz02ncpnfth0000gn/T/ipykernel_2441/1658380151.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always b

type  ambient_temperature  Capacity            Re           Rct
0     discharge                    4  1.674305 -4.976500e+11  1.055903e+12
1     impedance                   24  1.326543  5.605783e-02  2.009702e-01
2        charge                    4  1.326543 -4.976500e+11  1.055903e+12
3     impedance                   24  1.326543  5.319186e-02  1.647340e-01
4     discharge                    4  1.524366 -4.976500e+11  1.055903e+12
...         ...                  ...       ...           ...           ...
7560  impedance                   24  1.326543  9.680880e-02  1.548974e-01
7561  discharge                    4  1.020138 -4.976500e+11  1.055903e+12
7562     charge                    4  1.326543 -4.976500e+11  1.055903e+12
7563  discharge                    4  0.990759 -4.976500e+11  1.055903e+12
7564     charge                    4  1.326543 -4.976500e+11  1.055903e+12

[7565 rows x 5 columns]

In [21]:

label_encoder = LabelEncoder()
df['type'] = label_encoder.fit_transform(df['type'])
df.head()

type  ambient_temperature  Capacity            Re           Rct
0     1                    4  1.674305 -4.976500e+11  1.055903e+12
1     2                   24  1.326543  5.605783e-02  2.009702e-01
2     0                    4  1.326543 -4.976500e+11  1.055903e+12
3     2                   24  1.326543  5.319186e-02  1.647340e-01
4     1                    4  1.524366 -4.976500e+11  1.055903e+12

In [22]:
# Features (X) - All columns except 'ambient_temperature'
X = df.drop(columns=['ambient_temperature'])

# Target (y) - 'ambient_temperature' column
y = df['ambient_temperature']

# Split the data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the split data
print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')

X_train shape: (6052, 4)
X_test shape: (1513, 4)


In [23]:
# Initialize the StandardScaler
scaler = MinMaxScaler()

# Fit and transform the training data, then transform the test data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Check the scaled data
print(f'Scaled X_train: \n{X_train_scaled[:5]}')

Scaled X_train: 
[[1.00000000e+00 5.02450122e-01 9.99999999e-01 1.98111482e-10]
 [5.00000000e-01 4.55998175e-01 0.00000000e+00 1.00000000e+00]
 [5.00000000e-01 3.60527766e-02 0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 5.02450122e-01 0.00000000e+00 1.00000000e+00]
 [5.00000000e-01 5.35874070e-01 0.00000000e+00 1.00000000e+00]]


In [24]:
#model building starts 
# Initialize the ANN model
model = Sequential()

# Input layer and first hidden layer with 64 units and ReLU activation
model.add(Dense(units=64, activation='relu', input_dim=X_train_scaled.shape[1]))

# Add Dropout layer with 0.2 rate (20% dropout)
model.add(Dropout(0.2))
# Second hidden layer with 32 units and ReLU activation
model.add(Dense(units=32, activation='relu'))

# Add another Dropout layer
model.add(Dropout(0.2))


# Output layer with 1 unit (for regression output), using a linear activation
model.add(Dense(units=1, activation='linear'))

# Compile the model with Adam optimizer and Mean Squared Error loss (for regression)
model.compile(optimizer='adam', loss='mean_squared_error')

# Summary of the model architecture
model.summary()

/Users/shrutiagarwal/batterylifeprediction/project_env/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,433 (9.50 KB)

 Trainable params: 2,433 (9.50 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
# Train the model on the training data, using the test data for validation
history = model.fit(X_train_scaled, y_train, epochs=150, batch_size=32, validation_data=(X_test_scaled, y_test))

Epoch 1/150
190/190 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 409.1165 - val_loss: 88362.0547
Epoch 2/150
190/190 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 118.8120 - val_loss: 42359.6523
Epoch 3/150
190/190 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - loss: 112.8527 - val_loss: 28283.3281
Epoch 4/150
190/190 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - loss: 109.4142 - val_loss: 18072.1133
Epoch 5/150
190/190 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 107.5423 - val_loss: 8643.4004
Epoch 6/150
190/190 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 108.0092 - val_loss: 3628.0261
Epoch 7/150
190/190 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 106.9498 - val_loss: 1244.9679
Epoch 8/150
190/190 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 100.0037 - val_loss: 173.9036
Epoch 9/150
190/190 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 100.9417 - val_loss: 168.3795
Epoch 10/150
190/190 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 100.1247 - val_loss: 139.8858
Epoch 11/150
190/190 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - loss: 102.6979 -